#!/usr/bin/env bun
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

function extensionSuffix(platform: string): string {
  if (platform === "win32") return "dll";
  if (platform === "darwin") return "dylib";
  return "so";
}

function platformPackageName(platform: string, arch: string): string {
  const os = platform === "win32" ? "windows" : platform;
  return `sqlite-vec-${os}-${arch}`;
}

function generate(platform: string, arch: string): void {
  const packageName = platformPackageName(platform, arch);
  const ext = extensionSuffix(platform);
  const vec0Path = path.join(repoRoot, "node_modules", packageName, `vec0.${ext}`);

  if (!fs.existsSync(vec0Path)) {
    console.error(`sqlite-vec extension not found: ${vec0Path}`);
    console.error(`Install the platform package first: bun install ${packageName}`);
    process.exit(1);
  }

  const data = fs.readFileSync(vec0Path);
  const base64 = data.toString("base64");

  const output = `// Auto-generated by scripts/generate-vec-embed.ts. Do not edit manually.
import fs from "fs";
import path from "path";
import os from "os";
import { createHash } from "crypto";

const EMBEDDED_VEC0 = {
  platform: ${JSON.stringify(platform)},
  arch: ${JSON.stringify(arch)},
  ext: ${JSON.stringify(ext)},
  data: ${JSON.stringify(base64)},
};

function hashPrefix(data: string): string {
  return createHash("sha256").update(data).digest("hex").slice(0, 16);
}

export function getEmbeddedVec0Path(): string | null {
  if (process.platform !== EMBEDDED_VEC0.platform || process.arch !== EMBEDDED_VEC0.arch) {
    return null;
  }
  const prefix = hashPrefix(EMBEDDED_VEC0.data);
  const tmpDir = path.join(os.tmpdir(), \`prism-vec0-\${prefix}\`);
  fs.mkdirSync(tmpDir, { recursive: true });
  const tmpPath = path.join(tmpDir, \`vec0.\${EMBEDDED_VEC0.ext}\`);
  if (!fs.existsSync(tmpPath)) {
    fs.writeFileSync(tmpPath, Buffer.from(EMBEDDED_VEC0.data, "base64"));
    fs.chmodSync(tmpPath, 0o755);
  }
  return tmpPath;
}
`;

  const outPath = path.join(repoRoot, "engine", "sqlite-vec-embedded.ts");
  fs.writeFileSync(outPath, output);
  console.log(`Wrote embedded sqlite-vec extension for ${platform}-${arch} to ${outPath}`);
  console.log(`  Original: ${vec0Path} (${(data.length / 1024).toFixed(1)} KB)`);
}

const platform = process.argv[2] || process.platform;
const arch = process.argv[3] || process.arch;
generate(platform, arch);
