#!/usr/bin/env bash
# One-liner installer for prism-liquidity-agent.
# Usage: curl -fsSL https://raw.githubusercontent.com/irfndi/prism-liquidity-agent/main/scripts/install.sh | bash
set -euo pipefail

export HOME="${HOME:-/tmp}"
SHELL_NAME="${SHELL##*/}"
SHELL_NAME="${SHELL_NAME:-sh}"

REPO="${PRISM_REPO:-irfndi/prism-liquidity-agent}"
BIN_DIR="${PRISM_BIN_DIR:-$HOME/.local/bin}"
INSTALL_DIR="${PRISM_INSTALL_DIR:-$HOME/.prism}"
R2_BASE_URL="${PRISM_R2_URL:-https://pub-2f55c98709e74d1d900b89ec20f8f1fc.r2.dev}"
VERSION="${PRISM_VERSION:-}"
CHANNEL="${PRISM_CHANNEL:-stable}"
SKIP_SETUP="${PRISM_SKIP_SETUP:-}"
IS_OPTED_OUT=0
case "$(printf '%s' "${PRISM_FEEDBACK_OPT_OUT:-}" | tr '[:upper:]' '[:lower:]')" in
  1|true|yes|on) IS_OPTED_OUT=1 ;;
esac

log_step()  { printf "→ %s\n" "$*"; }
log_warn()  { printf "⚠ %s\n" "$*"; }
log_error() { printf "✘ %s\n" "$*" >&2; }
log_done()  { printf "✓ %s\n" "$*"; }

normalize_version() {
  printf '%s' "$1" \
    | sed -E 's/^v//; s/-[A-Za-z0-9.+].*$//' \
    | awk -F. '{ printf("%d.%d.%d\n", $1+0, ($2 ? $2 : 0)+0, ($3 ? $3 : 0)+0) }'
}

version_gte() {
  local installed min
  installed="$(normalize_version "$1")"
  min="$(normalize_version "$2")"
  [ "$(printf '%s\n%s\n' "$installed" "$min" | sort -V | head -n1)" = "$min" ]
}

ensure_bun() {
  if command -v bun >/dev/null 2>&1; then
    BUN_BIN="$(command -v bun)"
  else
    log_step "Bun not found; installing to \$HOME/.bun"
    if ! curl -fsSL https://bun.sh/install | bash >/dev/null 2>&1; then
      log_error "Failed to install Bun from bun.sh. Install it manually:"
      log_error "  curl -fsSL https://bun.sh/install | bash"
      return 1
    fi
    export BUN_INSTALL="$HOME/.bun"
    export PATH="$BUN_INSTALL/bin:$PATH"
    if ! command -v bun >/dev/null 2>&1; then
      log_error "Bun installer completed but 'bun' is still not on PATH."
      return 1
    fi
    BUN_BIN="$(command -v bun)"
  fi

  local current
  current="$("$BUN_BIN" --version 2>/dev/null || echo "unknown")"
  if ! version_gte "$current" "1.4.0-canary.1"; then
    log_error "Bun $current is installed but >= 1.4.0-canary.1 is required."
    log_error "Upgrade with:  curl -fsSL https://bun.sh/install | bash -s -- bun-v1.4.0-canary.1"
    return 1
  fi
  log_step "Bun $current at $BUN_BIN"
  return 0
}

detect_platform() {
  local os arch
  os="$(uname -s | tr '[:upper:]' '[:lower:]')"
  arch="$(uname -m)"
  case "$arch" in
    x86_64|amd64) arch="x64" ;;
    arm64|aarch64) arch="arm64" ;;
  esac
  printf '%s-%s' "$os" "$arch"
}

extension_suffix() {
  case "$1" in
    darwin*) printf 'dylib' ;;
    linux*)  printf 'so' ;;
    windows*) printf 'dll' ;;
    *)       printf 'so' ;;
  esac
}

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    log_error "Neither sha256sum nor shasum found; cannot verify checksum."
    exit 1
  fi
}

PLATFORM="$(detect_platform)"
EXT_SUFFIX="$(extension_suffix "$PLATFORM")"

if [ -z "$VERSION" ]; then
  log_step "Detecting latest ${CHANNEL} release..."
  LATEST_URL="${R2_BASE_URL}/releases/latest.json"
  if [ "$CHANNEL" != "stable" ]; then
    LATEST_URL="${R2_BASE_URL}/releases/channel/${CHANNEL}.json"
  fi
  VERSION="$(curl -fsSL "$LATEST_URL" 2>/dev/null | grep '"version":' | sed -E 's/.*"version": *"([^"]+)".*/\1/' || true)"
  if [ -z "$VERSION" ]; then
    log_error "Could not detect latest version from ${LATEST_URL}"
    exit 1
  fi
  log_step "Latest ${CHANNEL}: v${VERSION}"
fi

TARBALL_NAME="prism-v${VERSION}-${PLATFORM}.tar.gz"
TARBALL_URL="${R2_BASE_URL}/releases/v${VERSION}/${TARBALL_NAME}"
SHA256_URL="${TARBALL_URL}.sha256"

TMP_DIR="$(mktemp -d -t prism-install-XXXXXX)"
trap 'rm -rf "$TMP_DIR"' EXIT

log_step "Downloading ${TARBALL_NAME}"
if ! curl -fsSL "$TARBALL_URL" -o "${TMP_DIR}/${TARBALL_NAME}"; then
  log_error "Failed to download ${TARBALL_URL}"
  exit 1
fi

log_step "Verifying SHA-256 checksum..."
if ! curl -fsSL "$SHA256_URL" -o "${TMP_DIR}/${TARBALL_NAME}.sha256"; then
  log_error "Failed to download checksum from ${SHA256_URL}"
  exit 1
fi
EXPECTED_HASH="$(awk '{print $1}' "${TMP_DIR}/${TARBALL_NAME}.sha256")"
ACTUAL_HASH="$(sha256_of "${TMP_DIR}/${TARBALL_NAME}")"
if [ "$EXPECTED_HASH" != "$ACTUAL_HASH" ]; then
  log_error "SHA-256 mismatch: expected ${EXPECTED_HASH}, got ${ACTUAL_HASH}"
  exit 1
fi
log_done "Checksum verified"

log_step "Installing Prism to ${INSTALL_DIR}"
mkdir -p "$BIN_DIR" "$INSTALL_DIR"
rm -rf "$INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
tar -xzf "${TMP_DIR}/${TARBALL_NAME}" -C "$INSTALL_DIR"

if ! ensure_bun; then
  exit 1
fi

log_step "Writing wrapper ${BIN_DIR}/prism"
WRAPPER="$BIN_DIR/prism"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by Prism installer. Runs the compiled bundle.
export PRISM_INSTALL_DIR="$INSTALL_DIR"
export PRISM_VEC0_PATH="$INSTALL_DIR/lib/vec0.${EXT_SUFFIX}"
exec bun "$INSTALL_DIR/dist/cli/index.mjs" "\$@"
EOF
chmod +x "$WRAPPER"

mkdir -p "$HOME/.config/prism" "$HOME/.local/share/prism"

PATH_HAS_BIN_DIR=0
IFS=':' read -r -a _path_entries <<<"${PATH:-}"
for _entry in "${_path_entries[@]}"; do
  if [ "$_entry" = "$BIN_DIR" ]; then
    PATH_HAS_BIN_DIR=1
    break
  fi
done

echo ""
log_done "Install complete."
echo "  - Location: ${INSTALL_DIR}"
echo "  - Run:      ${BIN_DIR}/prism --version"
echo ""
if [ "$PATH_HAS_BIN_DIR" -eq 0 ]; then
  log_warn "$BIN_DIR is not on your current PATH."
  log_warn "Add it to your shell rc:"
  echo "    echo 'export PATH=\"\$PATH:$BIN_DIR\"' >> \"\$HOME/.${SHELL_NAME}rc\""
  echo "    export PATH=\"\$PATH:$BIN_DIR\""
  echo ""
fi

if [ -z "$SKIP_SETUP" ]; then
  log_step "Running Prism setup..."
  "$WRAPPER" setup
fi

# Anonymous install telemetry (opt-out via PRISM_FEEDBACK_OPT_OUT).
INSTALL_ID_FILE="$HOME/.config/prism/install-id"
if [ ! -s "$INSTALL_ID_FILE" ]; then
  INSTALL_ID="$(bun -e 'console.log(crypto.randomUUID())' 2>/dev/null || echo "")"
  if [ -z "$INSTALL_ID" ]; then
    UUID_HEX="$(od -An -tx1 -N16 /dev/urandom 2>/dev/null | tr -d ' \n')"
    if [ "${#UUID_HEX}" -eq 32 ]; then
      INSTALL_ID="${UUID_HEX:0:8}-${UUID_HEX:8:4}-${UUID_HEX:12:4}-${UUID_HEX:16:4}-${UUID_HEX:20:12}"
    fi
  fi
  if [ -n "$INSTALL_ID" ]; then
    echo "$INSTALL_ID" > "$INSTALL_ID_FILE"
    chmod 600 "$INSTALL_ID_FILE" 2>/dev/null || true
  fi
fi
INSTALL_ID="$(cat "$INSTALL_ID_FILE" 2>/dev/null || echo "")"
if [ -n "$INSTALL_ID" ] && [ "$IS_OPTED_OUT" -eq 0 ]; then
  PRISM_PLATFORM="$(uname -s | tr A-Z a-z)"
  PRISM_PAYLOAD="{\"installId\":\"$INSTALL_ID\",\"event\":\"install\",\"channel\":\"$CHANNEL\",\"platform\":\"$PRISM_PLATFORM\",\"version\":\"$VERSION\"}"
  curl -fsS --max-time 5 -X POST "${PRISM_API_URL:-https://prism-api.irfndi.workers.dev}/v1/installs/ping" \
    -H "Content-Type: application/json" \
    -d "$PRISM_PAYLOAD" >/dev/null 2>&1 &
fi
