#!/usr/bin/env bash
# One-liner installer for prism-liquidity-agent.
# Usage: curl -fsSL https://raw.githubusercontent.com/irfndi/prism-liquidity-agent/main/scripts/install.sh | bash
# Or with a pinned release tarball (faster, no git history):
#   PRISM_TARBALL_URL=<url> curl -fsSL .../install.sh | bash
set -euo pipefail

REPO="${PRISM_REPO:-irfndi/prism-liquidity-agent}"
INSTALL_DIR="${PRISM_INSTALL_DIR:-$HOME/.prism}"
BIN_DIR="${PRISM_BIN_DIR:-$HOME/.local/bin}"
TARBALL_URL="${PRISM_TARBALL_URL:-}"

echo "→ Installing prism to $INSTALL_DIR"
mkdir -p "$INSTALL_DIR" "$BIN_DIR"

# Detect or install Bun
BUN_INSTALLED=0
if ! command -v bun >/dev/null 2>&1; then
  echo "→ Bun not found; installing to $HOME/.bun"
  curl -fsSL https://bun.sh/install | bash
  export PATH="$HOME/.bun/bin:$PATH"
  BUN_INSTALLED=1
fi

if [ -n "$TARBALL_URL" ]; then
  echo "→ Downloading tarball: $TARBALL_URL"
  TMP_TARBALL="$(mktemp -t prism-install-XXXXXX.tar.gz)"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$TARBALL_URL" -o "$TMP_TARBALL"
  elif command -v wget >/dev/null 2>&1; then
    wget -q "$TARBALL_URL" -O "$TMP_TARBALL"
  else
    echo "✘ Neither curl nor wget found; install one and retry" >&2
    exit 1
  fi
  echo "→ Extracting to $INSTALL_DIR"
  rm -rf "$INSTALL_DIR"
  mkdir -p "$INSTALL_DIR"
  tar -xzf "$TMP_TARBALL" -C "$INSTALL_DIR"
  rm -f "$TMP_TARBALL"
  # Marker so 'prism update' / 'prism --version' can detect a non-git install.
  touch "$INSTALL_DIR/.tarball-install"
elif [ -d "$INSTALL_DIR/.git" ]; then
  echo "→ Updating existing install"
  # Resolve the default branch once; the symbolic ref can shift between
  # invocations and we want a single consistent value.
  DEFAULT_BRANCH=$(git -C "$INSTALL_DIR" symbolic-ref --short refs/remotes/origin/HEAD 2>/dev/null | sed 's|origin/||' || echo main)
  # Local modifications abort a plain --ff-only. Try a non-destructive path
  # first, then fall back to a hard reset against origin/<default-branch>.
  if (cd "$INSTALL_DIR" && git pull --ff-only 2>/dev/null); then
    :
  else
    echo "⚠ Local changes blocked fast-forward; stashing and retrying"
    if (cd "$INSTALL_DIR" && git stash && git pull --ff-only && git stash pop); then
      :
    else
      # Count stash entries before the reset so we can warn if any were
      # orphaned by a partial stash/pull/pop chain.
      STASH_COUNT=$(cd "$INSTALL_DIR" && git stash list 2>/dev/null | wc -l | tr -d ' ')
      echo "→ Update failed; resetting to origin/${DEFAULT_BRANCH}"
      (cd "$INSTALL_DIR" && git fetch origin && git reset --hard "origin/${DEFAULT_BRANCH}")
      if [ "${STASH_COUNT:-0}" -gt 0 ]; then
        echo "→ ${STASH_COUNT} stash entry/entries preserved (use 'git stash list' to inspect)"
      fi
    fi
  fi
elif [ -d "$INSTALL_DIR" ]; then
  # Exists but not a git repo (e.g. partial previous install). Nuke and reclone.
  echo "→ $INSTALL_DIR exists but is not a git repo; re-cloning"
  rm -rf "$INSTALL_DIR"
  git clone "https://github.com/$REPO.git" "$INSTALL_DIR"
else
  echo "→ Cloning $REPO"
  git clone "https://github.com/$REPO.git" "$INSTALL_DIR"
fi

# No --frozen-lockfile: an older Bun may fail to parse the current bun.lock
# and abort the install before dependencies land.
echo "→ Installing dependencies"
(cd "$INSTALL_DIR" && bun install)

echo "→ Running postinstall setup"
(cd "$INSTALL_DIR" && bun run setup:env || true)

# Write a wrapper script (not a symlink) so `prism` always runs from
# $INSTALL_DIR. Symlinking cli/index.ts directly would let prism setup
# write .env to the caller's cwd (it uses path.resolve('.env')) and let
# prism dev run `bun run dev` in the wrong directory.
if [ -w "$BIN_DIR" ]; then
  WRAPPER="$BIN_DIR/prism"
  # Use a plain `cd` rather than `env -C` for portability (env -C is a
  # non-standard extension, not present on every POSIX env).
  cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install.sh — always runs from the install root.
cd "$INSTALL_DIR" || exit 1
exec bun "$INSTALL_DIR/cli/index.ts" "\$@"
EOF
  chmod +x "$WRAPPER"
  echo "→ Wrote wrapper $BIN_DIR/prism (always runs in $INSTALL_DIR)"
else
  echo "→ $BIN_DIR is not writable; add $INSTALL_DIR/cli to your PATH manually"
fi

echo ""
echo "✓ Install complete."
if [ -n "$TARBALL_URL" ]; then
  echo "  - Source:   $INSTALL_DIR (tarball install — upgrade via 'prism update')"
else
  echo "  - Source:   $INSTALL_DIR (git install — upgrade via 'prism update' or rerun this script)"
fi
echo "  - Run:      $BIN_DIR/prism --version"
echo ""
echo "Next steps:"
if [ "$BUN_INSTALLED" -eq 1 ]; then
  echo "  1. Add to PATH (new shell):  export PATH=\"\$HOME/.bun/bin:$BIN_DIR:\$PATH\""
else
  echo "  1. Add to PATH if needed:    export PATH=\"$BIN_DIR:\$PATH\""
fi
echo "  2. Register an account:      prism register"
echo "  3. Configure:                prism setup --non-interactive --helius-key=your-helius-key"
echo "  4. Start trading:            prism dev"

INSTALL_ID_FILE="$HOME/.config/prism/install-id"
mkdir -p "$(dirname "$INSTALL_ID_FILE")"
if [ ! -s "$INSTALL_ID_FILE" ]; then
  INSTALL_ID="$(bun -e 'console.log(crypto.randomUUID())' 2>/dev/null || echo "")"
  if [ -z "$INSTALL_ID" ]; then
    UUID_HEX="$(od -An -tx1 -N16 /dev/urandom 2>/dev/null | tr -d ' \n')"
    if [ "${#UUID_HEX}" -eq 32 ]; then
      INSTALL_ID="${UUID_HEX:0:8}-${UUID_HEX:8:4}-${UUID_HEX:12:4}-${UUID_HEX:16:4}-${UUID_HEX:20:12}"
    fi
  fi
  if [ -n "$INSTALL_ID" ]; then
    echo "$INSTALL_ID" > "$INSTALL_ID_FILE"
    chmod 600 "$INSTALL_ID_FILE" 2>/dev/null || true
  fi
fi
INSTALL_ID="$(cat "$INSTALL_ID_FILE" 2>/dev/null || echo "")"
if [ -n "$INSTALL_ID" ]; then
  PRISM_VERSION="$(bun -e "console.log(require('$INSTALL_DIR/package.json').version)" 2>/dev/null || echo "")"
  PRISM_PLATFORM="$(uname -s | tr A-Z a-z)"
  PRISM_PAYLOAD="{\"installId\":\"$INSTALL_ID\",\"event\":\"install\",\"channel\":\"stable\",\"platform\":\"$PRISM_PLATFORM\""
  if [ -n "$PRISM_VERSION" ]; then
    PRISM_PAYLOAD="$PRISM_PAYLOAD,\"version\":\"$PRISM_VERSION\""
  fi
  PRISM_PAYLOAD="$PRISM_PAYLOAD}"
  curl -fsS --max-time 5 -X POST "${PRISM_API_URL:-https://prism-api.irfndi.workers.dev}/v1/installs/ping" \
    -H "Content-Type: application/json" \
    -d "$PRISM_PAYLOAD" >/dev/null 2>&1 &
fi
