// Post-install setup: generate a default .env if one is missing so the
// first `prism dev` does not crash on missing config. Idempotent — running
// it again on an existing .env is a no-op.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");
const ENV_PATH = process.env.PRISM_ENV_PATH ?? path.join(REPO_ROOT, ".env");

const DEFAULT_ENV = `# Prism — defaults generated by scripts/postinstall.js
# Override any of these for your environment.

# Paper trading is on by default; set PAPER_TRADING=false to execute on-chain.
PAPER_TRADING=true

# Scan interval (10 min) and strategy defaults — see engine/config-service.ts
SCAN_INTERVAL_MS=600000
MIN_POOL_TVL_USD=50000
MIN_FEE_IL_RATIO=1.2
VOLUME_AUTH_THRESHOLD=0.70
CONFIDENCE_THRESHOLD=0.65
TRAILING_STOP_PCT=0.10

# Database (relative to repo root by default)
SQLITE_DB_PATH=./prism.db

# Embedding backend: "fallback" (pure-JS, no ONNX download) or "onnx"
EMBEDDINGS_BACKEND=fallback

# Pool discovery: when WATCHLIST_POOLS is empty, this enables the
# screener-service to find pools automatically. Default on so a fresh
# install scans real pools without manual configuration.
ENABLE_POOL_DISCOVERY=true
DISCOVERY_MIN_TVL_USD=100000
DISCOVERY_MIN_FEE_RATIO=1.5

# Runtime: "stable" | "beta" | "dev"
UPDATE_CHANNEL=stable
`;

function main() {
  if (fs.existsSync(ENV_PATH)) {
    console.log(`✓ ${ENV_PATH} already exists; leaving it untouched.`);
  } else {
    fs.mkdirSync(path.dirname(ENV_PATH), { recursive: true });
    fs.writeFileSync(ENV_PATH, DEFAULT_ENV, { mode: 0o600 });
    console.log(`✓ Wrote default ${ENV_PATH}`);
  }

  console.log("");
  console.log('💬 Got feedback? Run:  prism feedback "<your message>"');
  console.log("   (set GITHUB_TOKEN to file issues on GitHub; otherwise stored locally)");
}

main();
