// Post-install setup: generate a default .env if one is missing so the
// first `prism dev` does not crash on missing config. Idempotent — running
// it again on an existing .env is a no-op.
import fs from "fs";
import path from "path";
import os from "os";
import { randomUUID } from "crypto";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");
const ENV_PATH = process.env.PRISM_ENV_PATH ?? path.join(REPO_ROOT, ".env");
const API_URL = process.env.PRISM_API_URL ?? "https://prism-api.irfndi.workers.dev";
const INSTALL_ID_FILE = path.join(os.homedir(), ".config", "prism", "install-id");

const DEFAULT_ENV = `# Prism — defaults generated by scripts/postinstall.js
# Override any of these for your environment.

# Paper trading is on by default; set PAPER_TRADING=false to execute on-chain.
PAPER_TRADING=true

# Scan interval (10 min) and strategy defaults — see engine/config-service.ts
SCAN_INTERVAL_MS=600000
MIN_POOL_TVL_USD=50000
MIN_FEE_IL_RATIO=1.2
VOLUME_AUTH_THRESHOLD=0.70
CONFIDENCE_THRESHOLD=0.65
TRAILING_STOP_PCT=0.10

# Database (relative to repo root by default)
SQLITE_DB_PATH=./prism.db

# Embedding backend: "fallback" (pure-JS, no ONNX download) or "onnx"
EMBEDDINGS_BACKEND=fallback

# Pool discovery: when WATCHLIST_POOLS is empty, this enables the
# screener-service to find pools automatically. Default on so a fresh
# install scans real pools without manual configuration.
ENABLE_POOL_DISCOVERY=true
DISCOVERY_MIN_TVL_USD=100000
DISCOVERY_MIN_FEE_RATIO=1.5

# Runtime: "stable" | "beta" | "dev"
UPDATE_CHANNEL=stable
`;

let cachedId = null;

function getOrCreateInstallId() {
  if (cachedId) return cachedId;
  try {
    if (fs.existsSync(INSTALL_ID_FILE)) {
      const existing = fs.readFileSync(INSTALL_ID_FILE, "utf-8").trim();
      if (existing.length >= 8 && existing.length <= 128) {
        cachedId = existing;
        return cachedId;
      }
    }
  } catch {
    cachedId = null;
  }
  const id = randomUUID();
  try {
    const dir = path.dirname(INSTALL_ID_FILE);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
    fs.writeFileSync(INSTALL_ID_FILE, id, { mode: 0o600 });
    fs.chmodSync(INSTALL_ID_FILE, 0o600);
  } catch {
    cachedId = id;
    return cachedId;
  }
  cachedId = id;
  return cachedId;
}

function pingInstall(event) {
  void (async () => {
    try {
      const pkgPath = path.join(REPO_ROOT, "package.json");
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
      const body = JSON.stringify({
        installId: getOrCreateInstallId(),
        event,
        version: pkg.version,
        channel: process.env.UPDATE_CHANNEL ?? "stable",
        platform: process.platform,
      });
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 3000);
      await fetch(`${API_URL}/v1/installs/ping`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body,
        signal: controller.signal,
      }).finally(() => clearTimeout(timeout));
    } catch {
      return;
    }
  })();
}

function main() {
  let isFirstRun = false;
  if (fs.existsSync(ENV_PATH)) {
    console.log(`✓ ${ENV_PATH} already exists; leaving it untouched.`);
  } else {
    fs.mkdirSync(path.dirname(ENV_PATH), { recursive: true });
    fs.writeFileSync(ENV_PATH, DEFAULT_ENV, { mode: 0o600 });
    isFirstRun = true;
    console.log(`✓ Wrote default ${ENV_PATH}`);
  }

  console.log("");
  console.log('💬 Got feedback? Run:  prism feedback "<your message>"');
  console.log("   (set GITHUB_TOKEN to file issues on GitHub; otherwise stored locally)");

  if (isFirstRun) {
    pingInstall("install");
  }
>>>>>>> d0a7d14 (feat(scripts): emit install ping from install.sh and postinstall.js)
}

main();
